# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/cpu_test.xdc

# Block Designs: bd/cpu_test/cpu_test.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_test || ORIG_REF_NAME==cpu_test} -quiet] -quiet

# IP: bd/cpu_test/ip/cpu_test_processing_system7_0_0/cpu_test_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_test_processing_system7_0_0 || ORIG_REF_NAME==cpu_test_processing_system7_0_0} -quiet] -quiet

# IP: bd/cpu_test/ip/cpu_test_axi_vdma_0_0/cpu_test_axi_vdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_test_axi_vdma_0_0 || ORIG_REF_NAME==cpu_test_axi_vdma_0_0} -quiet] -quiet

# IP: bd/cpu_test/ip/cpu_test_v_tc_0_0/cpu_test_v_tc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_test_v_tc_0_0 || ORIG_REF_NAME==cpu_test_v_tc_0_0} -quiet] -quiet

# IP: bd/cpu_test/ip/cpu_test_v_axi4s_vid_out_0_0/cpu_test_v_axi4s_vid_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_test_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==cpu_test_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/cpu_test/ip/cpu_test_rgb2lcd_0_0/cpu_test_rgb2lcd_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_test_rgb2lcd_0_0 || ORIG_REF_NAME==cpu_test_rgb2lcd_0_0} -quiet] -quiet

# IP: bd/cpu_test/ip/cpu_test_clk_wiz_0_0/cpu_test_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_test_clk_wiz_0_0 || ORIG_REF_NAME==cpu_test_clk_wiz_0_0} -quiet] -quiet

# IP: bd/cpu_test/ip/cpu_test_xbar_0/cpu_test_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_test_xbar_0 || ORIG_REF_NAME==cpu_test_xbar_0} -quiet] -quiet

# IP: bd/cpu_test/ip/cpu_test_ps7_0_axi_periph_0/cpu_test_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_test_ps7_0_axi_periph_0 || ORIG_REF_NAME==cpu_test_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/cpu_test/ip/cpu_test_rst_ps7_0_100M_0/cpu_test_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_test_rst_ps7_0_100M_0 || ORIG_REF_NAME==cpu_test_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/cpu_test/ip/cpu_test_axi_mem_intercon_0/cpu_test_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_test_axi_mem_intercon_0 || ORIG_REF_NAME==cpu_test_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/cpu_test/ip/cpu_test_axi_bram_ctrl_0_0/cpu_test_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_test_axi_bram_ctrl_0_0 || ORIG_REF_NAME==cpu_test_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/cpu_test/ip/cpu_test_blk_mem_gen_0_0/cpu_test_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_test_blk_mem_gen_0_0 || ORIG_REF_NAME==cpu_test_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/cpu_test/ip/cpu_test_PS_to_CPU_controller_0_0/cpu_test_PS_to_CPU_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_test_PS_to_CPU_controller_0_0 || ORIG_REF_NAME==cpu_test_PS_to_CPU_controller_0_0} -quiet] -quiet

# IP: bd/cpu_test/ip/cpu_test_blk_mem_gen_1_0/cpu_test_blk_mem_gen_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_test_blk_mem_gen_1_0 || ORIG_REF_NAME==cpu_test_blk_mem_gen_1_0} -quiet] -quiet

# IP: bd/cpu_test/ip/cpu_test_blk_mem_gen_2_0/cpu_test_blk_mem_gen_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_test_blk_mem_gen_2_0 || ORIG_REF_NAME==cpu_test_blk_mem_gen_2_0} -quiet] -quiet

# IP: bd/cpu_test/ip/cpu_test_proc_sys_reset_0_0/cpu_test_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_test_proc_sys_reset_0_0 || ORIG_REF_NAME==cpu_test_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/cpu_test/ip/cpu_test_ila_0_0/cpu_test_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_test_ila_0_0 || ORIG_REF_NAME==cpu_test_ila_0_0} -quiet] -quiet

# IP: bd/cpu_test/ip/cpu_test_axi_gpio_1_0/cpu_test_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_test_axi_gpio_1_0 || ORIG_REF_NAME==cpu_test_axi_gpio_1_0} -quiet] -quiet

# IP: bd/cpu_test/ip/cpu_test_xlconcat_0_0/cpu_test_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_test_xlconcat_0_0 || ORIG_REF_NAME==cpu_test_xlconcat_0_0} -quiet] -quiet

# IP: bd/cpu_test/ip/cpu_test_xbar_1/cpu_test_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_test_xbar_1 || ORIG_REF_NAME==cpu_test_xbar_1} -quiet] -quiet

# IP: bd/cpu_test/ip/cpu_test_axi_interconnect_0_0/cpu_test_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_test_axi_interconnect_0_0 || ORIG_REF_NAME==cpu_test_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/cpu_test/ip/cpu_test_AXI_LCD_TOU_DRI_0_0/cpu_test_AXI_LCD_TOU_DRI_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_test_AXI_LCD_TOU_DRI_0_0 || ORIG_REF_NAME==cpu_test_AXI_LCD_TOU_DRI_0_0} -quiet] -quiet

# IP: bd/cpu_test/ip/cpu_test_axi_wr_bram_0_2/cpu_test_axi_wr_bram_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_test_axi_wr_bram_0_2 || ORIG_REF_NAME==cpu_test_axi_wr_bram_0_2} -quiet] -quiet

# IP: bd/cpu_test/ip/cpu_test_axi_wr_bram_0_3/cpu_test_axi_wr_bram_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_test_axi_wr_bram_0_3 || ORIG_REF_NAME==cpu_test_axi_wr_bram_0_3} -quiet] -quiet

# IP: bd/cpu_test/ip/cpu_test_bluex_v_3_1_0_0/cpu_test_bluex_v_3_1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_test_bluex_v_3_1_0_0 || ORIG_REF_NAME==cpu_test_bluex_v_3_1_0_0} -quiet] -quiet

# IP: bd/cpu_test/ip/cpu_test_auto_pc_0/cpu_test_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_test_auto_pc_0 || ORIG_REF_NAME==cpu_test_auto_pc_0} -quiet] -quiet

# IP: bd/cpu_test/ip/cpu_test_auto_pc_1/cpu_test_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_test_auto_pc_1 || ORIG_REF_NAME==cpu_test_auto_pc_1} -quiet] -quiet

# IP: bd/cpu_test/ip/cpu_test_auto_pc_2/cpu_test_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_test_auto_pc_2 || ORIG_REF_NAME==cpu_test_auto_pc_2} -quiet] -quiet

# XDC: e:/Xilinx/FPGA_Prjs/dzy/cpu_test/cpu_test/cpu_test.gen/sources_1/bd/cpu_test/cpu_test_ooc.xdc
