# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Xilinx/FPGA_Prjs/dzy/cpu_test/cpu_test/cpu_test.srcs/sources_1/bd/cpu_test/ip/cpu_test_bluex_0_0/cpu_test_bluex_0_0.xci
# IP: The module: 'cpu_test_bluex_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Xilinx/FPGA_Prjs/dzy/cpu_test/cpu_test/cpu_test.gen/sources_1/bd/cpu_test/ip/cpu_test_bluex_0_0/src/bluex_v_2_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_test_bluex_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/Xilinx/FPGA_Prjs/dzy/cpu_test/cpu_test/cpu_test.srcs/sources_1/bd/cpu_test/ip/cpu_test_bluex_0_0/cpu_test_bluex_0_0.xci
# IP: The module: 'cpu_test_bluex_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Xilinx/FPGA_Prjs/dzy/cpu_test/cpu_test/cpu_test.gen/sources_1/bd/cpu_test/ip/cpu_test_bluex_0_0/src/bluex_v_2_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_test_bluex_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
