# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/bluex_v_2_1_wrapper.xdc

# Block Designs: bd/bluex_v_2_1/bluex_v_2_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bluex_v_2_1 || ORIG_REF_NAME==bluex_v_2_1} -quiet] -quiet

# IP: bd/bluex_v_2_1/ip/bluex_v_2_1_aux_ex_0_0/bluex_v_2_1_aux_ex_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bluex_v_2_1_aux_ex_0_0 || ORIG_REF_NAME==bluex_v_2_1_aux_ex_0_0} -quiet] -quiet

# IP: bd/bluex_v_2_1/ip/bluex_v_2_1_BJT_0_0/bluex_v_2_1_BJT_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bluex_v_2_1_BJT_0_0 || ORIG_REF_NAME==bluex_v_2_1_BJT_0_0} -quiet] -quiet

# IP: bd/bluex_v_2_1/ip/bluex_v_2_1_PC_0_0/bluex_v_2_1_PC_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bluex_v_2_1_PC_0_0 || ORIG_REF_NAME==bluex_v_2_1_PC_0_0} -quiet] -quiet

# IP: bd/bluex_v_2_1/ip/bluex_v_2_1_alu_ex_0_0/bluex_v_2_1_alu_ex_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bluex_v_2_1_alu_ex_0_0 || ORIG_REF_NAME==bluex_v_2_1_alu_ex_0_0} -quiet] -quiet

# IP: bd/bluex_v_2_1/ip/bluex_v_2_1_aux_id_0_0/bluex_v_2_1_aux_id_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bluex_v_2_1_aux_id_0_0 || ORIG_REF_NAME==bluex_v_2_1_aux_id_0_0} -quiet] -quiet

# IP: bd/bluex_v_2_1/ip/bluex_v_2_1_demux_id_0_0/bluex_v_2_1_demux_id_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bluex_v_2_1_demux_id_0_0 || ORIG_REF_NAME==bluex_v_2_1_demux_id_0_0} -quiet] -quiet

# IP: bd/bluex_v_2_1/ip/bluex_v_2_1_reg_heap_id_0_0/bluex_v_2_1_reg_heap_id_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bluex_v_2_1_reg_heap_id_0_0 || ORIG_REF_NAME==bluex_v_2_1_reg_heap_id_0_0} -quiet] -quiet

# IP: bd/bluex_v_2_1/ip/bluex_v_2_1_reg_wb_0_0/bluex_v_2_1_reg_wb_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bluex_v_2_1_reg_wb_0_0 || ORIG_REF_NAME==bluex_v_2_1_reg_wb_0_0} -quiet] -quiet

# IP: bd/bluex_v_2_1/ip/bluex_v_2_1_wrapper_mem_0_0/bluex_v_2_1_wrapper_mem_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bluex_v_2_1_wrapper_mem_0_0 || ORIG_REF_NAME==bluex_v_2_1_wrapper_mem_0_0} -quiet] -quiet

# IP: bd/bluex_v_2_1/ip/bluex_v_2_1_decoder_id_0_0/bluex_v_2_1_decoder_id_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bluex_v_2_1_decoder_id_0_0 || ORIG_REF_NAME==bluex_v_2_1_decoder_id_0_0} -quiet] -quiet

# IP: bd/bluex_v_2_1/ip/bluex_v_2_1_controller_0_0/bluex_v_2_1_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bluex_v_2_1_controller_0_0 || ORIG_REF_NAME==bluex_v_2_1_controller_0_0} -quiet] -quiet

# XDC: d:/MyWorks/Programs/Verilog/vivado/bluex_update/bluex_update.gen/sources_1/bd/bluex_v_2_1/bluex_v_2_1_ooc.xdc
