# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Xilinx/FPGA_Prjs/dzy/cpu_test/cpu_test/cpu_test.srcs/sources_1/bd/cpu_test/ip/cpu_test_auto_pc_2/cpu_test_auto_pc_2.xci
# IP: The module: 'cpu_test_auto_pc_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Xilinx/FPGA_Prjs/dzy/cpu_test/cpu_test/cpu_test.gen/sources_1/bd/cpu_test/ip/cpu_test_auto_pc_2/cpu_test_auto_pc_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_test_auto_pc_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/Xilinx/FPGA_Prjs/dzy/cpu_test/cpu_test/cpu_test.srcs/sources_1/bd/cpu_test/ip/cpu_test_auto_pc_2/cpu_test_auto_pc_2.xci
# IP: The module: 'cpu_test_auto_pc_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Xilinx/FPGA_Prjs/dzy/cpu_test/cpu_test/cpu_test.gen/sources_1/bd/cpu_test/ip/cpu_test_auto_pc_2/cpu_test_auto_pc_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_test_auto_pc_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
